from . import product_category
from . import product
from . import uom_category
from . import uom
from . import partner
from . import sale_order
from . import sale_order_line
from . import crm_team
from . import crm_lead
from . import crm_lead_line
from . import stock_warehouse
from . import stock_location
from . import stock_picking
from . import stock_move
from . import purchase_order_line
from . import purchase_order
from . import stock_inventory_line
from . import stock_inventory
from . import account_tax
