from . import product_category
from . import product
from . import uom_category
from . import uom
from . import partner
from . import sale_order
from . import sale_order_line
from . import crm_team
from . import crm_lead
from . import crm_lead_line
