from odoo import models, fields, api


class Lead(models.Model):
    _name = "crm.lead.ept"
    _description = "CRM Lead"

    partner_id = fields.Many2one(comodel_name="res.partner.ept", string="Partner", help="Customer")
    order_ids = fields.One2many(comodel_name="sale.order.ept", inverse_name="lead_id", string="Orders", help="Order generated by this lead", readonly=True)
    team_id = fields.Many2one(comodel_name="crm.team.ept", string="Team", help="Team who generated this lead")
    user_id = fields.Many2one(comodel_name="res.users", string="Sales Person", help="Sales Person who generated this lead")
    lead_line_ids = fields.One2many(comodel_name="crm.lead.line.ept", inverse_name="lead_id", string="Lead Lines", help="Product and it's quantity")
    state = fields.Selection(string="State",
                             help="State of the Lead",
                             selection=[('New', 'New'), ('Qualified', 'Qualified'), ('Proposition', 'Proposition'), ('Won', 'Won'), ('Lost', 'Lost')])
    won_date = fields.Date(string="Won Date", help="Date at which the lead is won")
    lost_reason = fields.Char(string="Lost Reason", help="Reason behind the loss of lead")
    next_followup_date = fields.Date(string="Follow Up Date", help="Date at which follow up from the customer has to be taken")
    partner_name = fields.Char(string="Partner Name", help="Name of the partner")
    partner_email = fields.Char(string="Partner Email", help="Email address of the partner")
    partner_country_id = fields.Many2one(comodel_name="res.country.ept", string="Country",
                                         help="Country where partner lives")
    partner_state_id = fields.Many2one(comodel_name="res.state.ept", string="Country",
                                         help="State where partner lives")
    partner_city_id = fields.Many2one(comodel_name="res.city.ept", string="City",
                                         help="City where partner lives")
    partner_phone_no = fields.Char(string="Partner Phone No", help="Phone number of the partner")

    def change_state_to_qualified(self):
        pass